name: Check Patched branches
on:
  workflow_dispatch:
  
  push:
    branches:
      - 'patch/**'
jobs:
  check-not-disruptive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

    - name: Build with Gradle
      run: ./gradlew :ms-example-usage:build

    - name: All tests passed
      if: success()
      run: echo "✅ All tests passed!"

    - name: Build failed
      if: failure()
      run: echo "❌ Build or tests failed"



